package com.portfolio.notifyhub.service;

import com.portfolio.notifyhub.api.CreateNotificationRequest;
import com.portfolio.notifyhub.api.CreateNotificationResponse;
import com.portfolio.notifyhub.domain.NotificationRequest;
import com.portfolio.notifyhub.domain.Status;
import com.portfolio.notifyhub.idempotency.IdempotencyService;
import com.portfolio.notifyhub.idempotency.IdempotencyConflictException;
import com.portfolio.notifyhub.idempotency.RequestFingerprint;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.QueryTimeoutException;
import org.springframework.data.redis.RedisConnectionFailureException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.exception.ConstraintViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
public class NotificationService {
    private static final Logger log = LoggerFactory.getLogger(NotificationService.class);
    private final NotificationPersistence persistence;
    private final IdempotencyService idempotencyService;

    public NotificationService(NotificationPersistence persistence, IdempotencyService idempotencyService) {
        this.persistence = persistence;
        this.idempotencyService = idempotencyService;
    }

    private boolean isIdempotencyConflict(Throwable error) {
        for (Throwable cause = error; cause != null; cause = cause.getCause()) {
            if (cause instanceof ConstraintViolationException violation) {
                // Constraint name generated by the V1 PostgreSQL migration.
                return "23505".equals(violation.getSQLState())
                        && "notification_request_idempotency_key_key".equals(violation.getConstraintName());
            }
        }
        return false;
    }

    @Transactional(propagation = Propagation.NOT_SUPPORTED)
    public CreateNotificationResponse create(CreateNotificationRequest request, String idempotencyKey) {
        String requestHash = RequestFingerprint.hash(request);
        UUID existingRequestId = null;
        boolean cacheAvailable = true;
        try {
            existingRequestId = idempotencyService.getExistingRequestId(idempotencyKey);
        } catch (RedisConnectionFailureException | QueryTimeoutException e) {
            cacheAvailable = false;
            log.warn("Redis lookup unavailable ({}); using PostgreSQL for idempotency",
                    e.getClass().getSimpleName());
        }
        if (existingRequestId != null) {
            var existing = persistence.findByIdempotencyKey(idempotencyKey);
            if (existing.isPresent()) return duplicateResponse(existing.get(), requestHash);
        }

        NotificationRequest notification = new NotificationRequest(
                idempotencyKey, requestHash, request.userId(), request.category(), request.channels(),
                request.templateId(), request.payload(), Status.ACCEPTED, request.scheduledAt());
        NotificationRequest saved;
        try {
            // The separate Spring bean commits or rolls back before this call returns or throws.
            saved = persistence.insert(notification);
        } catch (DataIntegrityViolationException e) {
            if (!isIdempotencyConflict(e)) throw e;
            NotificationRequest existing = persistence.findByIdempotencyKey(idempotencyKey)
                    .orElseThrow(() -> e);
            return duplicateResponse(existing, requestHash);
        }

        // Do not wait on Redis a second time when this request already observed an outage.
        if (cacheAvailable) {
            try {
                idempotencyService.claim(idempotencyKey, saved.getId());
            } catch (RedisConnectionFailureException | QueryTimeoutException e) {
                log.warn("Redis cache write unavailable ({}); returning committed notification {}",
                        e.getClass().getSimpleName(), saved.getId());
            }
        }
        return new CreateNotificationResponse(saved.getId(), saved.getStatus(), false);
    }
    private CreateNotificationResponse duplicateResponse(NotificationRequest existing, String requestHash) {
        String storedHash = existing.getRequestHash();
        // V1 rows created before fingerprinting can be compared using their persisted content.
        if (storedHash == null) {
            storedHash = RequestFingerprint.hash(new CreateNotificationRequest(existing.getUserId(),
                    existing.getCategory(), existing.getChannels(), existing.getTemplateId(),
                    existing.getPayload(), existing.getScheduledAt()));
        }
        if (!storedHash.equals(requestHash)) throw new IdempotencyConflictException();
        return new CreateNotificationResponse(existing.getId(), existing.getStatus(), true);
    }

}
